title: Skoleglæde.nu Batteri
description: Skoleglæde.nu Batteri er en ledsager-app til Skoleglæde.nu's brætspil om trivsel og sundhed for unge. Appen holder styr på hvert holds point ved at spillerne scanne QR-koder, der afsløres under spillet.
lang: da-DK
sass:
  style: :compressed
